# Put custom.scm right after directory
format = "$directory${custom.scm}$all"

[buf]
disabled = true

[character]
error_symbol = "[󰘧](bold red)"
success_symbol = "[󰘧](bold green)"

[directory]
truncate_to_repo = false

[dotnet]
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[git_branch]
disabled = true
symbol = " "
truncation_length = 18

[git_status]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[custom.scm]
when = "jj-starship detect"
shell = ["jj-starship", "--strip-bookmark-prefix", "rk/", "--truncate-name", "20", "--bookmarks-display-limit", "1"]
format = "$output "

[golang]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "

[gcloud]
disabled = true

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
style = "bold yellow"

[nodejs]
format = "[$symbol($version)]($style) "

[package]
disabled = true

